veeresht/CommPy

commpy/channels.py
Fix #9 
- Fix comparing operator 'is' to '=='
- Calculate abs from input signals before it is squared
=> Fix awgn() in channels.py

commpy/channelcoding/turbo.py, commpy/channels.py, commpy/modulation.py, commpy/sequences.py, doc/sphinxext/plot_directive.py
Replaced all the remaining xrange()s with range()s
Fixed up the modulate and __init__ methods in the Modem class and subclasses to work with Python 3 and newer numpys.
Tests good with Python 2.7.13 and Python 3.5.3, and with numpy 1.13.1.
=> Python 3 and modulation.py fixes

commpy/channels.py
This pull request updates type-checking for Complex ndarray in `commpy.channels.awgn` method.  Discussed in https://github.com/veeresht/CommPy/issues/19
=> Fix type checking for `Complex` ndarray

commpy/filters.py
docstring used to say filter creation functions returned  (h,time_index) tuple, but the actual return value had the (time_index ,h).  
This PR fixes the docstring.  Behavior is unchanged.
=> filters: corrected docstrings to match output tuple order

commpy/channelcoding/convcode.py
Add-on for Python 3 compatibility. In Python 3, the range() method returns a range data type that, for example, does not have a reverse () method.
=> Update method visualize()

README.md, commpy/channelcoding/README.md
The simulation of the convolutional codes was added.
=> New in channel codes README

THANKS.txt, commpy/examples/conv_encode_decode.py
I missed a Python 2 compatibility issue in the previous PR.
Do we agree to drop Python 2 compatibility since it will [retire in a few months](https://pythonclock.org/)? If so, one just have to change update the main readme with the right requirements.
=> [minor] Update Thanks file & Python 2 compatibility

commpy/channelcoding/convcode.py, commpy/channelcoding/tests/test_convcode.py, commpy/examples/conv_encode_decode.py
This PR makes small documentation changes to specifies the bit ordering when building treillis. At the moment, we use MSB first and this should appear in the doc. I also add a treillis in the example file to show how to use it properly.
The is some discussion about keeping MSB first or switching to LSB first as in Matlab going on in #62. This PR should be merge anyway as a short time fix. Then, if we opt for a change, the doc and the codes should be changed at the same time.
=> Specifies in the doc the bit ordering when building triellis (fix #62)

commpy/channelcoding/convcode.py, commpy/channelcoding/tests/test_ldpc.py, commpy/utilities.py
The current and previous implementations of dec2bitarray are a big chunk of time of the simulation.
This implementation is the fastest that I have found, comparing with the previously used ones.
Is based on this SO answer: https://stackoverflow.com/a/30227161
Test case to compare between the one available in the latest public release, the new currently in the code and the one that I'm proposing:
```
import itertools
import timeit
import numpy as np
from commpy.utilities import dec2bitarray
print(",".join(map(lambda x: str(x), list(dec2bitarray(100000, 121)))))
def proposed(number, size):
result = np.zeros(size, 'int')
i = 1
pox = 0
while i <= number:
if i & number:
result[size - pox - 1] = 1
i <<= 1
pox += 1
return result
print(",".join(map(lambda x: str(x), list(dec2ba(100000, 121))))) …
```
=> Change dec2bitarray to a faster implementation

commpy/channelcoding/convcode.py, commpy/links.py, commpy/utilities.py
Hello, 
In the past few weeks I have been using the library for some heavy number of runs and notice some bottlenecks.
Here are some contributions to patch some of the bottlenecks found to try to make the simulation faster.
- Added caching using an LRU cache in some functions that are slow and repeatedly called with same parameters;
- Change not-equal comparison of numpy arrays to bitwise xor since they are 1's and 0's;
- Reduce iterations in the _where_c function by taking advantage of numpy function to search for a value; 
Between each commit the following test was performed (based on conv_encode_decode):
```python
import math
import time
from datetime import timedelta
import numpy as np
import commpy.channelcoding.convcode as cc
import commpy.channels as chan
import commpy.links as lk …
```
=> Speed improvements

.travis.yml
The flag `-a 'slow'` in the Travis configuration file creates two issues:
- some bugs are not detected by Travis during commits and PRs. See for example #76 
- the coverage report is inconsistant since some functions are covered but the corresponding test is not executed. This has been already noted in #55 and some further experiments confirm this assumption.
Removing this flag would leads to a much longer computation time on Travis. I'm not aware of any limitation from Travis on the amount of computation that can be executed. Moreover, imo it is safer to have a reliable test that take a long time to execute rather than an inconsistant short one.
If the computation time is really an issue, we could split the tests in two command lines. The first command execute only the short tests and …
=> Remove slow flag in Travis configuration file

README.md, THANKS.txt, commpy/channelcoding/convcode.py, commpy/examples/conv_encode_decode.py, commpy/examples/wifi80211_conv_encode_decode.py, commpy/links.py, commpy/tests/test_links.py, commpy/tests/test_wifi80211.py, commpy/wifi80211.py
This adds the following changes:
- Adds an helper class that wraps the basics of an 802.11 simulation channel (the generator matrix according to the standard, coding and puncturing when needed, depuncturing and decoding);
- Adds the collection of more parameters of the simulation;
- Add chunk aggregation possibility. This looks like it is the same as sending a bigger chunk, but for accounting number of some parameters it makes a difference (i.e. number of chunk loss);
- [Breaking change] Changes from number of bits to simulate sending, to number of runs to simulate. The parameter always had that meaning and in the end I think it makes more sense. For a quick migration path, any user is advice to simple divide the number number of bits to simulate by the send chunk (and perform a …
=> Add Wifi 802.11 physical simulation

commpy/tests/test_wifi80211.py, commpy/wifi80211.py
QPSK is used for MCS 1 and 2, was using QAM by mistake.
=> Fix wrong modulation for mcs 1 and 2

commpy/links.py, commpy/tests/test_links.py
Commit bcc36ddc introduced a typing error in `link_performance`. Typing `received_msg` as `int` prevent soft detectors to work properly as LLRs are converted to integers. I can provide a minimal example for this but any test with soft detectors shows the error.
@eSoares: Since you hadded this, could you confirm that this is not need required so that I merge this PR before v0.6 release.
=> [Bug fix] Bad typing in links.py introduced in bcc36ddc

commpy/sequences.py, commpy/tests/test_sequences.py
Fix issue https://github.com/veeresht/CommPy/issues/70.
The CAZAC sequence was improperly coded, leading to non-zero cross-correlation terms when seq_length was an even number. This is fixed using the formula from https://en.wikipedia.org/wiki/Zadoff%E2%80%93Chu_sequence, thanks to the `cf` term.
Furthermore, additional checks are done to see if inputs are valid.
=> Fix CAZAC sequence

commpy/channelcoding/README.md
Fix both issues : https://github.com/veeresht/CommPy/issues/90 and https://github.com/veeresht/CommPy/issues/89.
This PR fixes different issues with the example code in `channelcoding/README.md` :
- `memory` should be a numpy 1D array
- `np.array([[0o171, 0o133]])` generator matrix was producing errors, I replaced by the one in the docstring examples `np.array([[5, 7]])`
- decoded messages and demodulated messages can be padded due to the modulation type.
=> Fix README code example for channelcoding

commpy/channelcoding/ldpc.py
`out_llrs` array was being overwritten by the output LLR values of a single block. Not only does this cause the returned `out_llrs` array to be incorrect, it may sometimes cause an error to be thrown. This occurs because the reshape at line 253 expects the `out_llrs` to contain LLR values for `n_blocks` different blocks, but it only contains the LLR values for a single block. 
This has been fixed by writing the output LLRs of each block to their corresponding position within the `out_llrs` array.
=> [Bug fix] ldpc_bp_decode

setup.py
I noticed that the design text files for gallager and wimax were not being installed even though they are listed in the package_data. I separated the string of directories for the files list so that each individual directory is added including the txt files in gallager/wimax.
=> Package_data files list fix

commpy/channels.py
np.complex is just an alias to python builtin `complex` and is deprecated as of numpy 1.20.
=> Remove usage of deprecated np.complex

setup.py
Hi guys, there is an issue preventing the installation of CommPy 0.7.0 via PIP in Windows. When attempting to do `pip install scikit-commpy` on Windows, version 0.6.0 is installed instead, due to a bug in setup.py in version 0.7.0. I don't know if the same issue appears in other OS.  Looking at the error logs and similar issues reported on StackOverflow, I found a quick fix.
In setup.py, change:
```
LONG_DESCRIPTION = open('README.md').read()
```
to
```
LONG_DESCRIPTION = open('README.md', encoding="utf8").read()
```
That should fix the pip installation on Windows. I tested it and this fix allowed me to install version 0.7.0 on my Windows PC.
=> Quick fix in setup.py 
